name: GC2
values:
  - key: domain
    value: ''
  - key: base
    value: ''
  - key: baresip_ip
    value: ''
  - key: 3pccsshdest
    value: ''
  - key: ws-webserver-socket
    value: ''
  - key: callId
    value: ''
  - key: web-provisioning-ip
    value: ''
  - key: proxysshdest
    value: ''
color: 120
